name: HELP (pwg)

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker
      # You may pin to the exact commit or the version.
      # uses: elgohr/Publish-Docker-Github-Action@f7aca2fea76a5218f3c76cd5933c3ba1d8008774
      uses: elgohr/Publish-Docker-Github-Action@3.02
      with:
        # The name of the image you would like to push
        name: harbor-registry.webgame.cluster.expertni-sluzby.cz/webgame/help
        # The login username for the registry
        username: ${{ secrets.DOCKER_HUB_NAME }}
        # The login password for the registry
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        # Set the default branch of your repository (default: master)
        default_branch: master
        # Use dockerfile when you would like to explicitly build a Dockerfile
        dockerfile: Dockerfile

    - name: Deploy to cluster
      uses: danielr1996/kubectl-action@1.0.0
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
        args: rollout restart deployment --namespace webgamecz webgamecz-help

    - name: Verify deployment
      uses: danielr1996/kubectl-action@1.0.0
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
        args: rollout status deployment --namespace webgamecz webgamecz-help
